**LSTM**:- Long short term memory is better than rnn because rnn not handle long sequences and in RNN has problem of **Vanishing Gradient**.
* In RNN there is pressure to maintain **LTC and STC** long term context or short term context in single line and **STC** are more dominant that reason in rnn they remind the latest news compare to older one .
** Conclusion/  difference:
** * 1) Lstm maintain different path for the "LTC and STC" both
** * 2) lstm contain more complex architecture compare to RNN
** In LSTM architecture it conatin 3 gate
** * 1) **Forget gate** : to remove something from cell state(ltm)
** * 2) **input gate** : to add something in cell state
** * 3) **output gate** : Calculate hidden state for next time stamp "or" based on current i/p decide long term memory me se kya chiz ko nikal ker ke as o/p dikhana he last ending . Based [o/p]. and Har given stage per **stm** creatre kerna h.

In [132]:
about = """About the Program
What is the course fee for  Data Science Mentorship Program 2023
The course follows a monthly subscription model where you have to make monthly payments of
What is the total duration of the course?
The total duration of the course is 7 months.
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at bhatsaab@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website -
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at bhatisaab@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at bhatisaab@gmail.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""



In [133]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [134]:
tokenizer = Tokenizer()

In [135]:
tokenizer.fit_on_texts([about])   # in this we send a multiple text in a tokenizer so we pass in form of list

In [136]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'for': 14,
 'all': 15,
 'sessions': 16,
 'in': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'session': 31,
 'our': 32,
 'paid': 33,
 'join': 34,
 'able': 35,
 'your': 36,
 'website': 37,
 'placement': 38,
 'monthly': 39,
 'not': 40,
 'get': 41,
 'yes': 42,
 'so': 43,
 'once': 44,
 'past': 45,
 'feb': 46,
 'assistance': 47,
 'fee': 48,
 'data': 49,
 'are': 50,
 'watch': 51,
 'month': 52,
 'by': 53,
 'mail': 54,
 'from': 55,
 'contact': 56,
 'us': 57,
 'at': 58,
 'or': 59,
 'rs': 60,
 'doubt': 61,
 'science': 62,
 'payments': 63,
 'duration': 64,
 '7': 65,
 'months': 66,
 'learning': 67,
 'case': 68,
 'here': 69,
 'part': 70,
 'google': 71,
 'see': 72,
 'late': 73,
 'dashboard': 74,
 'task': 75,
 'don’t': 76,
 'gma

In [137]:
len(tokenizer.word_index)

266

In [138]:
# we will find out sentences present in the dataset
input_sentences = []

for sentence in about.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]                    # this word covert into number and [0] is used to slice or come out single index

  for i in range(1, len(tokenized_sentence)):                                         # nested loop for picking up single line and then apply in this form [1,2,3]--->[1,2][1,2,3]  For this loop runs two times
    input_sentences.append(tokenized_sentence[:i+1])


In [139]:
input_sentences

[[87, 1],
 [87, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 48],
 [11, 7, 1, 12, 48, 14],
 [11, 7, 1, 12, 48, 14, 49],
 [11, 7, 1, 12, 48, 14, 49, 62],
 [11, 7, 1, 12, 48, 14, 49, 62, 88],
 [11, 7, 1, 12, 48, 14, 49, 62, 88, 13],
 [11, 7, 1, 12, 48, 14, 49, 62, 88, 13, 143],
 [1, 12],
 [1, 12, 89],
 [1, 12, 89, 5],
 [1, 12, 89, 5, 39],
 [1, 12, 89, 5, 39, 29],
 [1, 12, 89, 5, 39, 29, 90],
 [1, 12, 89, 5, 39, 29, 90, 30],
 [1, 12, 89, 5, 39, 29, 90, 30, 2],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8, 4],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8, 4, 26],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8, 4, 26, 39],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8, 4, 26, 39, 63],
 [1, 12, 89, 5, 39, 29, 90, 30, 2, 8, 4, 26, 39, 63, 6],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 91],
 [11, 7, 1, 91, 64],
 [11, 7, 1, 91, 64, 6],
 [11, 7, 1, 91, 64, 6, 1],
 [11, 7, 1, 91, 64, 6, 1, 12],
 [1, 91],
 [1, 91, 64],
 [1, 91, 64, 6],
 [1, 91, 64, 6, 1],
 [1, 91, 64, 6, 1, 12],
 [1

In [140]:
# in above output the shape is not equal for this we apply "padding"  --> for padding we require max sentence length
max_len = max(len(x) for x in input_sentences)
print(max_len)

57


In [141]:
# padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sentences, max_len, padding = 'pre')                                                                       # In this we pass 3 parameter in the pad sequence
padded_input_sequences

array([[  0,   0,   0, ...,   0,  87,   1],
       [  0,   0,   0, ...,  87,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 263,  18, 264],
       [  0,   0,   0, ...,  18, 264, 265],
       [  0,   0,   0, ..., 264, 265, 266]], dtype=int32)

In [142]:
X = padded_input_sequences[:,:-1]

Convert the data into **Supervised data** in with X and y

In [143]:
y = padded_input_sequences[:,-1]

In [144]:
X.shape

(818, 56)

In [145]:
y.shape

(818,)

In [146]:
X

array([[  0,   0,   0, ...,   0,   0,  87],
       [  0,   0,   0, ...,   0,  87,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 263,  18],
       [  0,   0,   0, ..., 263,  18, 264],
       [  0,   0,   0, ...,  18, 264, 265]], dtype=int32)

In [147]:
y

array([  1,  13,   7,   1,  12,  48,  14,  49,  62,  88,  13, 143,  12,
        89,   5,  39,  29,  90,  30,   2,   8,   4,  26,  39,  63,   6,
         7,   1,  91,  64,   6,   1,  12,  91,  64,   6,   1,  12,   7,
        65,  66,   7,   1,  92,   6,   1,  88,  13,   9,  19, 144,   1,
       145, 146, 147, 148,  14,  49,  62, 149,  14,  49,  62,  14, 152,
        67, 153,  94,  95,  10, 156,   1, 157,  92,  69,  96,  67,  20,
        97,  19,   5,  70,   6,  21,  13,  97,  20,  96,  67, 158,  50,
        40,   5,  70,   6,  21, 159, 160,  22,   3,  99,   5, 100,  31,
         9,   3,  41,   5, 101,   6,   1,  31,  15,  32,  16,  50, 161,
        43, 102,  22,   2,  99,   5,  31,   2,  10, 162, 163,  20,  51,
         1, 101,  10,   3, 164,   1, 103, 165,  21,  71, 167,   4,  72,
        52,  53,  52, 104, 168,   6,   1,  12,   7,   1, 104,  64,   6,
        15,   1, 100,  16,  15,   1,  16, 170, 105, 171,   7,   1, 172,
       173,  53,   1, 174, 175,   1,  16,   9,   3,  19, 177,  8

Text_generator --> supervised--> classification ---> multiclass_classification   "So we use **OneHot Encoding"

Convert output into categorical which can help to predict

In [148]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 267)               # num_classes = size of the (tokenizer +1) --> tokenizer.word_index = index start from 1 n

In [149]:
y.shape

(818, 267)

In [150]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [151]:
# building the architecture
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [152]:
model = Sequential()
model.add(Embedding(267, 100, input_length = 56))      # 267 total no. of word counts , output dense vector 100 number  input_length =56 becoz each row contain 56 words
model.add(LSTM(150))                                  # her lstm gate per kitne node honge
#model.add(LSTM(150))
model.add(Dense(267, activation = 'softmax'))        # 267 utne node dalne honge jitne apne vocabulary words h

In [153]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 56, 100)           26700     
                                                                 
 lstm_3 (LSTM)               (None, 150)               150600    
                                                                 
 dense_3 (Dense)             (None, 267)               40317     
                                                                 
Total params: 217617 (850.07 KB)
Trainable params: 217617 (850.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [154]:
model.fit(X,y,epochs=100)

Epoch 1/100
26/26 [==============================] - 3s 57ms/step - loss: 5.4009 - accuracy: 0.0538
Epoch 2/100
26/26 [==============================] - 1s 57ms/step - loss: 5.0327 - accuracy: 0.0807
Epoch 3/100
26/26 [==============================] - 2s 58ms/step - loss: 4.9536 - accuracy: 0.0807
Epoch 4/100
26/26 [==============================] - 2s 85ms/step - loss: 4.9204 - accuracy: 0.0807
Epoch 5/100
26/26 [==============================] - 2s 58ms/step - loss: 4.8884 - accuracy: 0.0807
Epoch 6/100
26/26 [==============================] - 1s 57ms/step - loss: 4.8377 - accuracy: 0.0807
Epoch 7/100
26/26 [==============================] - 1s 54ms/step - loss: 4.7107 - accuracy: 0.1027
Epoch 8/100
26/26 [==============================] - 1s 55ms/step - loss: 4.5282 - accuracy: 0.1357
Epoch 9/100
26/26 [==============================] - 1s 57ms/step - loss: 4.3244 - accuracy: 0.1638
Epoch 10/100
26/26 [==============================] - 1s 57ms/step - loss: 4.1036 - accuracy: 0.1956

In [155]:
import numpy as np

text = 'mail'

* 1) tokenize   --> text_to_sequences([text])  
* 2) padding    --> pad_sequences(input, max_length, padding )
* 3) predict    --> model.predict(padding)

In [156]:
# now we can predict

import time
text = "what is "
for i in range(5):
  #tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]                                     # in this they accept the multiple input so pass in the list
  #padding
  padded_token_text = pad_sequences([token_text],maxlen = 56, padding = 'pre')
  # print(padded_token_text)
  # predict
  pos = np.argmax(model.predict(padded_token_text))                                       # in this is used to define kis position per higher probablity h

  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " "+ word
      print(text)
      time.sleep(2)

1/1 [==============================] - 1s 557ms/step
what is  the
1/1 [==============================] - 0s 15ms/step
what is  the language
1/1 [==============================] - 0s 18ms/step
what is  the language spoken
1/1 [==============================] - 0s 16ms/step
what is  the language spoken by
1/1 [==============================] - 0s 16ms/step
what is  the language spoken by the


In [157]:
tokenizer.word_index.items()

dict_items([('the', 1), ('you', 2), ('i', 3), ('to', 4), ('a', 5), ('of', 6), ('is', 7), ('have', 8), ('will', 9), ('can', 10), ('what', 11), ('course', 12), ('program', 13), ('for', 14), ('all', 15), ('sessions', 16), ('in', 17), ('on', 18), ('be', 19), ('and', 20), ('this', 21), ('if', 22), ('am', 23), ('pay', 24), ('payment', 25), ('make', 26), ('we', 27), ('do', 28), ('subscription', 29), ('where', 30), ('session', 31), ('our', 32), ('paid', 33), ('join', 34), ('able', 35), ('your', 36), ('website', 37), ('placement', 38), ('monthly', 39), ('not', 40), ('get', 41), ('yes', 42), ('so', 43), ('once', 44), ('past', 45), ('feb', 46), ('assistance', 47), ('fee', 48), ('data', 49), ('are', 50), ('watch', 51), ('month', 52), ('by', 53), ('mail', 54), ('from', 55), ('contact', 56), ('us', 57), ('at', 58), ('or', 59), ('rs', 60), ('doubt', 61), ('science', 62), ('payments', 63), ('duration', 64), ('7', 65), ('months', 66), ('learning', 67), ('case', 68), ('here', 69), ('part', 70), ('google